# Aim: To Preprocess the Dataset for Machine Learning

In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import scipy

In [330]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [331]:
import sklearn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [332]:
import sys
import os
import math
import csv
import json

## Helper Methods and Variables

In [333]:
def sentence_to_snake_case(sentence):
    # Split the sentence into words, convert to lowercase, and join with underscores
    snake_case = '_'.join(word.lower() for word in sentence.split())
    return snake_case

In [334]:
useless_cols = ['CustomerID', 'Count', 'Country', 'State', 'City', \
                'Zip Code', 'Lat Long', 'Churn Score', 'Churn Label', 'CLTV', 'Churn Reason']

In [335]:
y_col = ["Churn Value"]

## Prepare the Data

In [336]:
os.getcwd()

'C:\\D Drive\\University of Washington\\Study\\Quarter 2\\DATA 557\\Project\\ML'

In [337]:
data = pd.read_csv('../data/Telco_customer_churn_cleaned.csv')

In [338]:
data.head()

,Unnamed: 0,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [339]:
data.head()

,Unnamed: 0,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [340]:
data.shape

(7043, 34)

In [341]:
data = data.rename(columns = lambda column: sentence_to_snake_case(column))

In [342]:
data.head()

,unnamed:_0,customerid,count,country,state,city,zip_code,lat_long,latitude,longitude,...,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_label,churn_value,churn_score,cltv,churn_reason
0,0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [343]:
# Leaving in Customer ID just in case
useless_cols = [sentence_to_snake_case(column) for column in useless_cols]

In [344]:
y_col = [sentence_to_snake_case(column) for column in y_col]

In [345]:
y_col

['churn_value']

In [346]:
# Drop the first column "Unnamed" and the useless columns
data = data.drop([data.columns[0]] + useless_cols, axis=1)

In [347]:
data.head()

,latitude,longitude,gender,senior_citizen,partner,dependents,tenure_months,phone_service,multiple_lines,internet_service,...,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,monthly_charges,total_charges,churn_value
0,33.964131,-118.272783,Male,No,No,No,2,Yes,No,DSL,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
1,34.059281,-118.307420,Female,No,No,Yes,2,Yes,No,Fiber optic,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
2,34.048013,-118.293953,Female,No,No,Yes,8,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1
3,34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1
4,34.039224,-118.266293,Male,No,No,Yes,49,Yes,Yes,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1

## Divide the dataset into train and test test

In [348]:
RNG = np.random.RandomState(seed=420)

In [349]:
train, test = train_test_split(data, test_size=0.1, shuffle=True, random_state=RNG)

In [350]:
train.shape

(6338, 22)

In [351]:
test.shape

(705, 22)

## Pre-process the data

### Normalize

**Remember to save normalization details of train data, to apply to test data**

Pipeline transforms automatically do so for us.

In [352]:
dtypes = data.dtypes

In [353]:
# Prepare to Standardize all numeric columns except Churn Value
numeric_cols = list(data.select_dtypes(include=['int64', 'float64']))
numeric_cols = [column for column in numeric_cols if column not in y_col]
numeric_cols

['latitude', 'longitude', 'tenure_months', 'monthly_charges', 'total_charges']

In [354]:
# Pipeline is to maintain consistency
standardization_transformer = Pipeline(steps=[('scaler', StandardScaler())])

In [355]:
# ColumnTransformer helps standardize only selected columns
preprocessor = ColumnTransformer(
    transformers=[('num', standardization_transformer, numeric_cols)],
    remainder='passthrough'  # This leaves the rest of the columns in the dataset unchanged
)

In [356]:
preprocessed_train_array = preprocessor.fit(train).transform(train)

In [357]:
# train

Convert the preprocessed arrays into pandas dataframe, by taking into account the correct column names, and the correct column types.

In [358]:
preprocessed_columns = [col.split('__')[1] for col in preprocessor.get_feature_names_out()]
# preprocessed_columns

## Warning!! Bad Coding Practice Alert

In [359]:
# Instead of mapping preprocessed_columns with the old data.columns and getting the dtypes
# for now we will proceed with hard-coding logic
# Because columns that have prefix num are obviously float
# While other columns are either object or can be treated as object (except Churn Value which will separately be made int64)
preprocessed_column_types = ['float64' if col.split('__')[0]=='num' else 'object' for col in preprocessor.get_feature_names_out()]

In [360]:
preprocessed_column_types[-1] = 'int64'

In [361]:
preprocessed_column_dtypes = {preprocessed_columns[i]: preprocessed_column_types[i] for i in range(len(preprocessed_columns))}

In [362]:
preprocessed_train = pd.DataFrame(data=preprocessed_train_array, columns=preprocessed_columns)
preprocessed_train = preprocessed_train.astype(preprocessed_column_dtypes)

In [363]:
preprocessed_train.head()

,latitude,longitude,tenure_months,monthly_charges,total_charges,gender,senior_citizen,partner,dependents,phone_service,...,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,churn_value
0,-0.498158,-0.371946,1.125328,1.295086,1.621985,Male,No,Yes,Yes,Yes,...,No,Yes,No,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),0
1,-1.423199,1.358143,-0.501284,-1.516232,-0.813905,Female,No,No,No,Yes,...,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Credit card (automatic),0
2,0.444907,-1.026476,-0.623280,0.965322,-0.289477,Male,No,No,No,Yes,...,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,1
3,1.202459,-0.117674,-0.135296,-1.514566,-0.760886,Female,No,No,No,Yes,...,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,0
4,-0.899465,0.660012,0.678010,0.653879,0.714169,Female,No,No,No,Yes,...,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,0

In [364]:
# preprocessed_train.dtypes

In [365]:
preprocessed_test_array = preprocessor.transform(test)

In [366]:
preprocessed_test = pd.DataFrame(data=preprocessed_test_array, columns=preprocessed_columns)
preprocessed_test = preprocessed_test.astype(preprocessed_column_dtypes)

In [367]:
preprocessed_test.head()

,latitude,longitude,tenure_months,monthly_charges,total_charges,gender,senior_citizen,partner,dependents,phone_service,...,online_security,online_backup,device_protection,tech_support,streaming_tv,streaming_movies,contract,paperless_billing,payment_method,churn_value
0,1.077896,-1.383298,1.206658,1.331726,1.772881,Female,Yes,Yes,No,Yes,...,Yes,No,Yes,No,Yes,Yes,One year,Yes,Electronic check,0
1,-0.903949,0.703809,0.596679,-1.479591,-0.589838,Male,No,No,No,Yes,...,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),0
2,-0.863037,0.738054,-0.948603,-0.165534,-0.766100,Male,No,No,No,Yes,...,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,0
3,0.495985,-1.031974,-0.013301,0.868725,0.270326,Female,Yes,No,No,Yes,...,No,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,0
4,0.898898,-0.799467,-1.151929,0.184215,-0.881114,Female,No,No,No,Yes,...,No,No,No,No,No,No,Month-to-month,No,Electronic check,1

In [368]:
# preprocessed_test.dtypes

### Split Datasets into X and y

(Not useful if using statsmodels api)

In [369]:
X_columns = list(preprocessed_train.columns)

In [370]:
X_columns = [column for column in X_columns if column not in y_col]

In [371]:
# X_columns

In [372]:
X_train, y_train = preprocessed_train[X_columns], preprocessed_train[y_col]

In [373]:
X_test, y_test = preprocessed_test[X_columns], preprocessed_test[y_col]

### Dimensionality Reduction?

Maybe later. Not relevant to Lasso Regression

## Run Lasso Logistic Regression

In [374]:
# preprocessed_column_types

In [375]:
# preprocessed_train_array

In [376]:
# preprocessed_train.dtypes

In [377]:
preprocessed_train.columns

Index(['latitude', 'longitude', 'tenure_months', 'monthly_charges',
       'total_charges', 'gender', 'senior_citizen', 'partner', 'dependents',
       'phone_service', 'multiple_lines', 'internet_service',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract', 'paperless_billing',
       'payment_method', 'churn_value'],
      dtype='object')

In [378]:
def formulaGenerator(data, y_col = ['']):
    x_cols = [column for column in list(data.columns) if column not in y_col]
    formula = f'{y_col[0]} ~'
    for index, column in enumerate(x_cols):
        if index != 0: formula = f'{formula} +'
        if data.dtypes[column] in ['int64', 'float64']: formula = f'{formula} {column}'
        else: formula = f'{formula} C({column})'
    return formula

In [381]:
formula = formulaGenerator(preprocessed_train, y_col)
formula

'churn_value ~ latitude + longitude + tenure_months + monthly_charges + total_charges + C(gender) + C(senior_citizen) + C(partner) + C(dependents) + C(phone_service) + C(multiple_lines) + C(internet_service) + C(online_security) + C(online_backup) + C(device_protection) + C(tech_support) + C(streaming_tv) + C(streaming_movies) + C(contract) + C(paperless_billing) + C(payment_method)'

In [404]:
model = smf.logit(formula = formula, data = preprocessed_train)
results = model.fit_regularized(method='l1', alpha=10, QC_verbose=False)

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.6931471805599452
            Iterations: 5
            Function evaluations: 1
            Gradient evaluations: 1

In [405]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:            churn_value   No. Observations:                 6338
Model:                          Logit   Df Residuals:                     6338
Method:                           MLE   Df Model:                           -1
Date:                Mon, 04 Mar 2024   Pseudo R-squ.:                 -0.1993
Time:                        13:30:22   Log-Likelihood:                -4393.2
converged:                       True   LL-Null:                       -3663.2
Covariance Type:            nonrobust   LLR p-value:                       nan
================================================================================================================
                                                   coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                             0        nan        nan        nan         nan         nan
C(gender)[T.Male]                                     0        nan        nan        nan         nan         nan
C(senior_citizen)[T.Yes]                              0        nan        nan        nan         nan         nan
C(partner)[T.Yes]                                     0        nan        nan        nan         nan         nan
C(dependents)[T.Yes]                                  0        nan        nan        nan         nan         nan
C(phone_service)[T.Yes]                               0        nan        nan        nan         nan         nan
C(multiple_lines)[T.No phone service]                 0        nan        nan        nan         nan         nan
C(multiple_lines)[T.Yes]                              0        nan        nan        nan         nan         nan
C(internet_service)[T.Fiber optic]                    0        nan        nan        nan         nan         nan
C(internet_service)[T.No]                             0        nan        nan        nan         nan         nan
C(online_security)[T.No internet service]             0        nan        nan        nan         nan         nan
C(online_security)[T.Yes]                             0        nan        nan        nan         nan         nan
C(online_backup)[T.No internet service]               0        nan        nan        nan         nan         nan
C(online_backup)[T.Yes]                               0        nan        nan        nan         nan         nan
C(device_protection)[T.No internet service]           0        nan        nan        nan         nan         nan
C(device_protection)[T.Yes]                           0        nan        nan        nan         nan         nan
C(tech_support)[T.No internet service]                0        nan        nan        nan         nan         nan
C(tech_support)[T.Yes]                                0        nan        nan        nan         nan         nan
C(streaming_tv)[T.No internet service]                0        nan        nan        nan         nan         nan
C(streaming_tv)[T.Yes]                                0        nan        nan        nan         nan         nan
C(streaming_movies)[T.No internet service]            0        nan        nan        nan         nan         nan
C(streaming_movies)[T.Yes]                            0        nan        nan        nan         nan         nan
C(contract)[T.One year]                               0        nan        nan        nan         nan         nan
C(contract)[T.Two year]                               0        nan        nan        nan         nan         nan
C(paperless_billing)[T.Yes]                           0        nan        nan        nan         nan         nan
C(payment_method)[T.Credit card (automatic)]          0        nan        nan        nan         nan         nan
C(payment_method)[T.Electronic check]                 0        nan        nan        nan         nan         nan
C(payment_method)[T.Mailed check]                     0        nan        nan        nan         nan         nan
latitude                                              0        nan        nan        nan         nan         nan
longitude                                             0        nan        nan        nan         nan         nan
tenure_months                                         0        nan        nan        nan         nan         nan
monthly_charges                                       0        nan        nan        nan         nan         nan
total_charges                                         0        nan        nan        nan         nan         nan
================================================================================================================
"""

In [144]:
param_grid = {'C': np.logspace(-5, 3, 2)}

In [145]:
param_list = list(ParameterGrid(param_grid))

In [146]:
coefficients = []

In [147]:
for params in param_list:
    # Set the parameters to the model
    model.set_params(**params)
    
    # Fit the model
    model.fit(X_train, y_train)
    
    # Store the coefficients
    coefficients.append(model.coef_)

ValueError: could not convert string to float: '3413-DHLPB'

## Helper Methods for Logistic Regression, Cross-Validation